# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: release
cache: packages
latex: false
after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

matrix:
  include:
    - os: linux
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.2
