# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false
after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
    - os: osx
      r: release
      osx_image: xcode8.3
