on: [push, pull_request]

name: Continuous integration

jobs:
  macOS-checks:
    name: macOS Checks
    runs-on: macOS-latest
    strategy:
      matrix:
        r: ['3.6', '3.5', 'devel']
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }} 
      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes")' -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Check
        run: Rscript -e 'install.packages("rcmdcheck")' -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"))'
