on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes")' -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Check
        run: Rscript -e 'install.packages("rcmdcheck")' -e "rcmdcheck::rcmdcheck(manual = FALSE, error_on='error')"
